const IMAGES = {
  digital : new URL('./images/digital.png', import.meta.url).href,
  orbit : new URL('./images/orbit.png', import.meta.url).href,
  createAccount : new URL('./images/createAccount.png', import.meta.url).href,
  photo : new URL('./images/Photo.png', import.meta.url).href,
  grib : new URL('./images/grib.png', import.meta.url).href,
  wallet : new URL('./images/wallet.png', import.meta.url).href,

  Avatar1 : new URL('./avatars/Avatar1.png', import.meta.url).href,
  Avatar2 : new URL('./avatars/Avatar2.png', import.meta.url).href,
  Avatar3 : new URL('./avatars/Avatar3.png', import.meta.url).href,
  Avatar4 : new URL('./avatars/Avatar4.png', import.meta.url).href,
  Avatar5 : new URL('./avatars/Avatar5.png', import.meta.url).href,
  Avatar6 : new URL('./avatars/Avatar6.png', import.meta.url).href,
  Avatar7 : new URL('./avatars/Avatar7.png', import.meta.url).href,
  Avatar8 : new URL('./avatars/Avatar8.png', import.meta.url).href,
  Avatar9 : new URL('./avatars/Avatar9.png', import.meta.url).href,
  Avatar10 : new URL('./avatars/Avatar10.png', import.meta.url).href,
  Avatar11 : new URL('./avatars/Avatar11.png', import.meta.url).href,
  Avatar12 : new URL('./avatars/Avatar12.png', import.meta.url).href,
  Avatar13 : new URL('./avatars/Avatar1.png', import.meta.url).href,
  Avatar14 : new URL('./avatars/Avatar2.png', import.meta.url).href,
  Avatar15: new URL('./avatars/Avatar3.png', import.meta.url).href,
  Avatar16 : new URL('./avatars/Avatar4.png', import.meta.url).href,
  Avatar17 : new URL('./avatars/Avatar5.png', import.meta.url).href,
  Avatar18 : new URL('./avatars/Avatar6.png', import.meta.url).href,
  Avatar19 : new URL('./avatars/Avatar7.png', import.meta.url).href,
  Avatar20 : new URL('./avatars/Avatar8.png', import.meta.url).href,

  icon1 : new URL('./icons/Basketball.svg', import.meta.url).href,
  icon2 : new URL('./icons/BookmarksSimple.svg', import.meta.url).href,
  icon3 : new URL('./icons/Camera.svg', import.meta.url).href,
  icon4 : new URL('./icons/Coinbase.png', import.meta.url).href,
  icon5 : new URL('./icons/CollectionIcon.png', import.meta.url).href,
  icon6 : new URL('./icons/DiscordLogo.svg', import.meta.url).href,
  icon7 : new URL('./icons/EnvelopeSimple.svg', import.meta.url).href,
  icon8 : new URL('./icons/InstagramLogo.svg', import.meta.url).href,
  icon9 : new URL('./icons/logo.svg', import.meta.url).href,
  icon10 : new URL('./icons/MagicWand.svg', import.meta.url).href,
  icon11 : new URL('./icons/Metamask.png', import.meta.url).href,
  icon12 : new URL('./icons/MusicNotes.svg', import.meta.url).href,
  icon13 : new URL('./icons/PaintBrush.svg', import.meta.url).href,
  icon14 : new URL('./icons/Planet.svg', import.meta.url).href,
  icon15 : new URL('./icons/RocketLaunch.svg', import.meta.url).href,
  icon16 : new URL('./icons/WalletIcon.png', import.meta.url).href,
  icon17 : new URL('./icons/EarningIcon.png', import.meta.url).href,
  icon18 : new URL('./icons/Storefront.svg', import.meta.url).href,
  icon19 : new URL('./icons/Swatches.svg', import.meta.url).href,
  icon20 : new URL('./icons/TwitterLogo.svg', import.meta.url).href,
  icon21 : new URL('./icons/VideoCamera.svg', import.meta.url).href,
  icon22 : new URL('./icons/WalletConnect.png', import.meta.url).href,
  icon23 : new URL('./icons/YoutubeLogo.svg', import.meta.url).href,

  nft1 : new URL('./nft/nft1.png', import.meta.url).href,
  nft2 : new URL('./nft/nft2.png', import.meta.url).href,
  nft3 : new URL('./nft/nft3.png', import.meta.url).href,
  nft4 : new URL('./nft/nft4.png', import.meta.url).href,
  nft5 : new URL('./nft/nft5.png', import.meta.url).href,
  nft6 : new URL('./nft/nft6.png', import.meta.url).href,
  nft7 : new URL('./nft/nft7.png', import.meta.url).href,
  nft8 : new URL('./nft/nft8.png', import.meta.url).href,
  nft9 : new URL('./nft/nft9.png', import.meta.url).href,
  nft10 : new URL('./nft/nft10.png', import.meta.url).href
}

export default IMAGES;